const data = {
    products: [
        {
            _id: '1',
            name: 'cat food',
            category: 'foods',
            image:'/images/foods_1.jpg',
            price: 42,
            brand: 'Yes',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality cat food',
        },
        {
            _id: '2',
            name: 'cat food2',
            category: 'foods',
            image:'/images/foods_1.jpg',
            price: 42,
            brand: 'Yes',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality cat food',
        },
        {
            _id: '3',
            name: 'cat food',
            category: 'foods',
            image:'/images/foods_1.jpg',
            price: 42,
            brand: 'Yes',
            rating: 3.5,
            numReviews: 14,
            description: 'high quality cat food',
        },
        {
            _id: '4',
            name: 'cat food',
            category: 'foods',
            image:'/images/foods_1.jpg',
            price: 42,
            brand: 'Yes',
            rating: 3,
            numReviews: 14,
            description: 'high quality cat food',
        },
        {
            _id: '5',
            name: 'cat food',
            category: 'foods',
            image:'/images/foods_1.jpg',
            price: 42,
            brand: 'Yes',
            rating: 4,
            numReviews: 14,
            description: 'high quality cat food',
        }
    ]
}